#FROM node:6.9.0
FROM openthings/ubuntu-nodejs:ARM64

WORKDIR /home/weave

COPY package.json /home/weave/

ENV NPM_CONFIG_LOGLEVEL=http NPM_CONFIG_PROGRESS=true 
ENV HTTPS_PROXY=192.168.1.88:9999 GIT_SSL_NO_VERIFY=true NVM_DIR="/root/.nvm" 

RUN	git clone --progress https://github.com/creationix/nvm.git && \
	cd nvm && ./install.sh

#	export NVM_DIR="/root/.nvm" && \
#	[ -s "$NVM_DIR/nvm.sh" ] && \
#	. "$NVM_DIR/nvm.sh" 

RUN	. "/root/.nvm/nvm.sh" && \
	nvm ls 
#	nvm install 6.9.2

#RUN 	npm config set proxy=http://192.168.1.88:9999 && \
#RUN	npm config set registry=https://registry.npm.taobao.org && \
#	npm install -g npm

#RUN	npm install minimatch openssl semver && npm install

#COPY webpack.local.config.js webpack.production.config.js server.js .babelrc .eslintrc .eslintignore /home/weave/

#CMD ["node"]
